# Generated by Django 5.2.5 on 2026-08-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_loginattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("before_due", "마감 전"), ("overdue", "마감 초과")], max_length=20)),
                ("scheduled_for", models.DateTimeField(verbose_name="알림 기준 시각")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="발송 시각")),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_records", to="tracker.assignment")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-scheduled_for"]},
        ),
        migrations.AddConstraint(
            model_name="assignmentnotification",
            constraint=models.UniqueConstraint(fields=("assignment", "user", "scheduled_for"), name="unique_assignment_notification_schedule"),
        ),
    ]
