# Generated by Django 5.2.17 on 2026-08-12 04:11

from django.db import migrations, models


def preserve_custom_titles(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    Message = apps.get_model("chat", "Message")
    for conversation in Conversation.objects.all():
        first_user = (
            Message.objects.filter(conversation=conversation, role="user")
            .order_by("created_at", "id")
            .first()
        )
        automatic_titles = {"새 대화", "이전 대화"}
        if first_user:
            automatic_titles.add(first_user.content[:40])
        if conversation.title not in automatic_titles:
            conversation.title_is_custom = True
            conversation.save(update_fields=["title_is_custom"])


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title_is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(preserve_custom_titles, migrations.RunPython.noop),
    ]
